---
- gather_facts: False
  name: enable virtual media auto-attach
  hosts: all
  tasks:
    - name: set virtual media to auto-attach mode
      raw: racadm config -g cfgRacVirtual -o cfgVirMediaAttached 2
      register: result
      failed_when: "'ERROR' in result.stdout or 'COMMAND PROCESSING FAILED' in result.stdout or 'error' in result.stdout or result.rc != 0"
    - debug: var=result
