---
- gather_facts: False
  name: enable ipmi management over lan
  hosts: all
  tasks:
    - name: enable ipmi management over lan
      raw: racadm set iDRAC.IPMILan.Enable 1
      register: result
      failed_when: "'ERROR' in result.stdout or 'COMMAND PROCESSING FAILED' in result.stdout or 'error' in result.stdout or result.rc != 0"
    - debug: var=result
