---
- gather_facts: False
  name: check for racadm
  hosts: all
  tasks:
    - name: racadm check
      raw: racadm
      register: result
      # DRAC v5, >5, plus the default failure for other cases (like invalid password)
      failed_when: "'not found' in result.stdout or 'COMMAND NOT RECOGNIZED' in result.stdout or 'error' in result.stdout or result.rc != 0"
    # uncomment for debug output
    # - debug: var=result
