---
- gather_facts: False
  name: reset DRAC
  hosts: "{{ hosts }}"
  tasks:
    - name: run racreset
      raw: racadm racreset soft
      register: result
      failed_when: "'ERROR' in result.stdout or 'COMMAND PROCESSING FAILED' in result.stdout or 'error' in result.stdout or result.rc != 0"
