---
- gather_facts: False
  name: enable web ui
  hosts: all
  tasks:
    - name: enable web server
      raw: racadm config -g cfgRacTuning -o cfgRacTuneWebServerEnable 1
      register: result
      failed_when: "'ERROR' in result.stdout or 'COMMAND PROCESSING FAILED' in result.stdout or 'error' in result.stdout or result.rc != 0"
    - debug: var=result
